dist: bionic
env:
   global:
     - CONAN_VERSION: "1.6.0"
    
linux: &linux
   os: linux
   dist: xenial
   sudo: required
   language: python
   python: "3.7"
   services:
     - docker
osx: &osx
   os: osx
   language: generic
matrix:
   include:
      - <<: *linux
        dist: bionic
        # env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=conanio/gcc7
      - <<: *linux
        dist: bionic
        # env: CONAN_CLANG_VERSIONS=6.0 CONAN_DOCKER_IMAGE=conanio/clang60
      - <<: *osx
        osx_image: xcode10
        env: CONAN_APPLE_CLANG_VERSIONS=10.1 CONAN_VERSION=1.6.0

install:
  - chmod +x .ci/install.sh
  - ./.ci/install.sh

script:
  - chmod +x .ci/run.sh
  - ./.ci/run.sh
